### ISSUE TITLE
not all zipcodes uniquely identify cities

### ISSUE THREAD

**Issue by spencerroan** [Ziptastic/ziptastic-jquery-plugin#2]
I did a quick google search and found this for instance:

https://getsatisfaction.com/foursquare/topics/issues_with_multiple_cities_in_same_zip_code
http://www.flickr.com/groups/zonetagusers/discuss/72057594074475952/

I'm sure there are many more instances of this phenomenon, especially in rural areas.
I do not know what the % of false positives you will have, but just thought I'd pipe up.

**Comment by daspecster** [comment]
Fantastic conversation! I'm closing but it will always be here.
