### ISSUE TITLE
Problem with non-US zipcodes 

### ISSUE THREAD

**Issue by notnami** [Ziptastic/ziptastic-jquery-plugin#5]
I tried a Moscow (Russia) postcode 123557, and British MK18 5EH. Both gave me 404s. My current Chicago zipcode worked expectedly fine.

**Comment by daspecster** [comment]
So right now, the URL format is /<version>/<country>/<postal_code>. This issue hasn't come up in the last 3 years. I'm closing unless someone wants to bring it up again!  That said, we do have a reverse geocoding feature coming which will allow you to use the HTML5 geolocation APIs.
